#!/bin/bash

ACTION=$1
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$ACTION" = "drop_db" ]; then
	. $ROOT_DIR/scripts/db_data/drop_db.sh
fi

if [ "$ACTION" = "load_db" ]; then
	. $ROOT_DIR/please drop_db
	. $ROOT_DIR/scripts/db_data/create_db.sh
fi

if [ "$ACTION" = "load_dummy" ]; then
	. $ROOT_DIR/scripts/db_data/load_dummy.sh
fi

if [ "$ACTION" = "start" ]; then
	python manage.py runserver

fi

echo "FINISHED!"