# THIS FILE SHOULD NOT BE PUSHED TO GIT

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'sagelyio@gmail.com'
EMAIL_HOST_PASSWORD = 'LOL WHAT ARE YOU HACKING US?  WHAT A LOSER'
EMAIL_PORT = 587
